"""init

Revision ID: a67e082479de
Revises: 
Create Date: 2025-08-01 18:16:54.089282+00:00

"""
import pgvector.sqlalchemy
from typing import Sequence, Union
from enum import StrEnum
import json
import copy
import base64


from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text, TypeDecorator
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import Dialect

from aci.common.db.custom_sql_types import EncryptedSecurityCredentials, EncryptedSecurityScheme

# --- Custom Enums ---
class SecurityScheme(StrEnum):
    NO_AUTH = "no_auth"
    API_KEY = "api_key"
    HTTP_BASIC = "http_basic"
    HTTP_BEARER = "http_bearer"
    OAUTH2 = "oauth2"

class Protocol(StrEnum):
    REST = "rest"
    CONNECTOR = "connector"


# revision identifiers, used by Alembic.
revision: str = 'a67e082479de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('security_schemes', EncryptedSecurityScheme(), nullable=False),
    sa.Column('default_security_credentials_by_scheme', EncryptedSecurityCredentials(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # NOTE: We do not create the 'users' table in the 'auth' schema.
    # It is managed by Supabase and already exists.
    op.create_table('app_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('security_scheme', sa.Enum(SecurityScheme, name='securityscheme'), nullable=False),
    sa.Column('security_scheme_overrides', EncryptedSecurityScheme(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('all_functions_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_functions', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.Enum(Protocol, name='protocol'), nullable=False),
    sa.Column('protocol_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('linked_accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('security_scheme', sa.Enum(SecurityScheme, name='securityscheme'), nullable=False),
    sa.Column('security_credentials', EncryptedSecurityCredentials(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_id', name='uc_user_app_linked_account')
    )
    op.create_table('profiles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secrets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('linked_account_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.BYTEA(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_account_id'], ['linked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_account_id', 'key', name='uc_linked_account_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    op.drop_table('profiles')
    op.drop_table('linked_accounts')
    op.drop_table('functions')
    op.drop_table('app_configurations')
    # NOTE: We do not drop the 'users' table as it's managed by Supabase.
    op.drop_table('apps')
    
    # Manually drop the enum types
    sa.Enum(SecurityScheme, name='securityscheme').drop(op.get_bind(), checkfirst=False)
    sa.Enum(Protocol, name='protocol').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###