"""Add recurring automations

Revision ID: 58c9c40d859f
Revises: f65bf9b2980e
Create Date: 2025-08-22 18:46:09.658873+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58c9c40d859f'
down_revision: Union[str, None] = 'f65bf9b2980e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_runs', sa.Column('message', sa.Text(), nullable=False))
    op.drop_column('automation_runs', 'ai_message')
    op.add_column('automation_templates', sa.Column('is_deep', sa.Boolean(), nullable=False))
    op.add_column('automations', sa.Column('cron_schedule', sa.String(length=255), nullable=True))
    op.add_column('automations', sa.Column('is_deep', sa.Boolean(), nullable=False))
    op.add_column('automations', sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'is_recurring')
    op.drop_column('automations', 'is_deep')
    op.drop_column('automations', 'cron_schedule')
    op.drop_column('automation_templates', 'is_deep')
    op.add_column('automation_runs', sa.Column('ai_message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('automation_runs', 'message')
    # ### end Alembic commands ###
