"""Allow disabling functions

Revision ID: 08dc1f91cde4
Revises: 5afaafd17513
Create Date: 2025-08-06 17:02:42.604813+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08dc1f91cde4"
down_revision: Union[str, None] = "5afaafd17513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linked_accounts",
        sa.Column(
            "disabled_functions",
            postgresql.ARRAY(sa.String(length=255)),
            nullable=False,
            server_default=sa.text("ARRAY[]::VARCHAR[]"),
        ),
    )
    op.drop_column("linked_accounts", "enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linked_accounts",
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("linked_accounts", "disabled_functions")
    # ### end Alembic commands ###
