"""add_banner_url

Revision ID: a732204a00ab
Revises: 72a1e765aa18
Create Date: 2025-09-06 17:06:31.548054+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a732204a00ab'
down_revision: Union[str, None] = '72a1e765aa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_templates', sa.Column('banner_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_templates', 'banner_image_url')
    # ### end Alembic commands ###
