"""add tags to automation templates

Revision ID: f65bf9b2980e
Revises: 9ce45af6ba8c
Create Date: 2025-08-20 17:35:32.553053+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f65bf9b2980e'
down_revision: Union[str, None] = '9ce45af6ba8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_templates', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('automation_templates', 'tags')
    # ### end Alembic commands ###
