"""fix usage

Revision ID: ac55df85358b
Revises: f40a2985dbc9
Create Date: 2025-10-26 12:51:42.503398+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac55df85358b'
down_revision: Union[str, None] = 'f40a2985dbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usage_user_year_month'), table_name='user_usage')
    op.drop_constraint(op.f('uq_user_year_month'), 'user_usage', type_='unique')
    op.create_index('ix_user_usage_user_id_created_at', 'user_usage', ['user_id', 'created_at'], unique=False)
    op.drop_column('user_usage', 'month')
    op.drop_column('user_usage', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_usage', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_user_usage_user_id_created_at', table_name='user_usage')
    op.create_unique_constraint(op.f('uq_user_year_month'), 'user_usage', ['user_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_usage_user_year_month'), 'user_usage', ['user_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###
