"""changes to temp file table

Revision ID: 6e87e7caf969
Revises: 2ba0f0c5f256
Create Date: 2025-08-09 11:15:16.647811+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e87e7caf969'
down_revision: Union[str, None] = '2ba0f0c5f256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('temp_files', sa.Column('filer_path', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'temp_files', ['filer_path'])
    op.drop_column('temp_files', 'file_url')
    op.drop_column('temp_files', 'fid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_files', sa.Column('fid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('temp_files', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'temp_files', type_='unique')
    op.drop_column('temp_files', 'filer_path')