"""add_webhook_events_table

Revision ID: bb9aeb3a6966
Revises: 177c91094774
Create Date: 2025-10-25 12:16:16.690585+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9aeb3a6966'
down_revision: Union[str, None] = '177c91094774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index('ix_webhook_events_provider_event_type', 'webhook_events', ['provider', 'event_type'], unique=False)
    op.create_index('ix_webhook_events_user_created', 'webhook_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_user_id'), 'webhook_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_user_id'), table_name='webhook_events')
    op.drop_index('ix_webhook_events_user_created', table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_event_type', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
