"""automation runs

Revision ID: 5fe2dcb3e5d6
Revises: 29c4a1fa8764
Create Date: 2025-08-24 13:42:10.229227+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fe2dcb3e5d6'
down_revision: Union[str, None] = '29c4a1fa8764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_run_artifacts')
    op.add_column('artifacts', sa.Column('run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'artifacts', 'automation_runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'run_id')
    op.create_table('automation_run_artifacts',
    sa.Column('automation_run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('automation_run_artifacts_artifact_id_fkey')),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], name=op.f('automation_run_artifacts_automation_run_id_fkey')),
    sa.PrimaryKeyConstraint('automation_run_id', 'artifact_id', name=op.f('automation_run_artifacts_pkey'))
    )
    # ### end Alembic commands ###
