"""embedding size

Revision ID: b28ecb778605
Revises: 054b43ffc3c3
Create Date: 2025-08-12 19:36:58.854119+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28ecb778605'
down_revision: Union[str, None] = '054b43ffc3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update the 'functions' table
    op.execute("""
    ALTER TABLE functions
    ALTER COLUMN embedding TYPE vector(1536)
    USING array_fill(0, ARRAY[1536])::vector(1536);
    """)

    # Update the 'apps' table
    op.execute("""
    ALTER TABLE apps
    ALTER COLUMN embedding TYPE vector(1536)
    USING array_fill(0, ARRAY[1536])::vector(1536);
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOTE: Replace '768' with your previous embedding dimension if it was different.
    OLD_EMBEDDING_DIMENSION = 768

    # Revert the 'functions' table
    op.execute(f"""
    ALTER TABLE functions
    ALTER COLUMN embedding TYPE vector({OLD_EMBEDDING_DIMENSION})
    USING array_fill(0, ARRAY[{OLD_EMBEDDING_DIMENSION}])::vector({OLD_EMBEDDING_DIMENSION});
    """)

    # Revert the 'apps' table
    op.execute(f"""
    ALTER TABLE apps
    ALTER COLUMN embedding TYPE vector({OLD_EMBEDDING_DIMENSION})
    USING array_fill(0, ARRAY[{OLD_EMBEDDING_DIMENSION}])::vector({OLD_EMBEDDING_DIMENSION});
    """)

    # ### end Alembic commands ###