"""remove plans

Revision ID: 177c91094774
Revises: 66bcc1a6b583
Create Date: 2025-10-19 18:20:33.019789+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177c91094774'
down_revision: Union[str, None] = '66bcc1a6b583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('duration', postgresql.ENUM('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'LIFETIME', name='planduration'), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('revenue_cat_product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('automation_runs_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('voice_chat_minutes_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('automations_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trial_days', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('apps_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey')),
    sa.UniqueConstraint('revenue_cat_product_id', name=op.f('plans_revenue_cat_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
