"""automation templates search

Revision ID: 412721a3f547
Revises: 5fe2dcb3e5d6
Create Date: 2025-08-24 14:31:42.810170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '412721a3f547'
down_revision: Union[str, None] = '5fe2dcb3e5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Alembic will autogenerate the column addition.
    op.add_column('automation_templates', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    
    # 2. Alembic will autogenerate the index creation.
    op.create_index('ix_automation_templates_search_vector', 'automation_templates', ['search_vector'], unique=False, postgresql_using='gin')
    
    # --- MANUALLY ADDED SQL ---
    
    # 3. Manually create the trigger function using op.execute()
    op.execute("""
        CREATE OR REPLACE FUNCTION public.update_automation_template_search_vector()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector :=
                to_tsvector('english', COALESCE(NEW.name, '')) ||
                to_tsvector('english', COALESCE(NEW.description, '')) ||
                to_tsvector('english', array_to_string(NEW.tags, ' '));
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # 4. Manually create the trigger itself.
    op.execute("""
        CREATE TRIGGER tsvector_update_trigger
        BEFORE INSERT OR UPDATE ON public.automation_templates
        FOR EACH ROW EXECUTE FUNCTION public.update_automation_template_search_vector();
    """)

    # 5. Manually backfill the data for existing rows.
    op.execute("""
        UPDATE public.automation_templates
        SET search_vector = 
            to_tsvector('english', COALESCE(name, '')) ||
            to_tsvector('english', COALESCE(description, '')) ||
            to_tsvector('english', array_to_string(tags, ' '));
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- MANUALLY ADDED SQL FOR REVERSING THE CHANGES ---
    op.execute("DROP TRIGGER IF EXISTS tsvector_update_trigger ON public.automation_templates;")
    op.execute("DROP FUNCTION IF EXISTS public.update_automation_template_search_vector();")
    
    # 2. Alembic will autogenerate the index removal.
    op.drop_index('ix_automation_templates_search_vector', table_name='automation_templates')
    
    # 1. Alembic will autogenerate the column removal.
    op.drop_column('automation_templates', 'search_vector')
    
    # ### end Alembic commands ###