"""Add plans api

Revision ID: 01f1ffb395cf
Revises: a1b2c3d4e5f6
Create Date: 2025-10-09 18:33:14.711090+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f1ffb395cf'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'LIFETIME', name='planduration'), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('revenue_cat_product_id', sa.String(length=255), nullable=False),
    sa.Column('automation_runs_limit', sa.BigInteger(), nullable=False),
    sa.Column('voice_chat_minutes_limit', sa.BigInteger(), nullable=False),
    sa.Column('automations_limit', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trial_days', sa.BigInteger(), nullable=True),
    sa.Column('apps_limit', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revenue_cat_product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
