"""Add user id in artifacts

Revision ID: 054b43ffc3c3
Revises: e8c9c9d47036
Create Date: 2025-08-10 11:46:36.211572+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054b43ffc3c3'
down_revision: Union[str, None] = 'e8c9c9d47036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'artifacts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'user_id')
    # ### end Alembic commands ###
