"""Add description to automations

Revision ID: 29c4a1fa8764
Revises: d7c0721a92cb
Create Date: 2025-08-23 15:01:18.542631+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '29c4a1fa8764'
down_revision: Union[str, None] = 'd7c0721a92cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('automation_templates', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('automations', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'description')
    op.alter_column('automation_templates', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
