"""automations

Revision ID: 9ce45af6ba8c
Revises: 19fe6aabdacf
Create Date: 2025-08-20 17:09:16.587989+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ce45af6ba8c'
down_revision: Union[str, None] = '19fe6aabdacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False, comment="A Jinja2 template for the automation's goal."),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variable_names', postgresql.ARRAY(sa.String()), nullable=False, comment='List of variable names used in the goal template.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('automation_template_apps',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['automation_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'app_id')
    )
    op.create_table('automations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('last_run_status', sa.Enum('success', 'failure', 'in_progress', 'never_run', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_linked_accounts',
    sa.Column('automation_id', sa.String(), nullable=False),
    sa.Column('linked_account_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['linked_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_runs',
    sa.Column('automation_id', sa.String(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('ai_message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', 'in_progress', 'never_run', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_run_artifacts',
    sa.Column('automation_run_id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['automation_run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('automation_run_id', 'artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('automation_run_artifacts')
    op.drop_table('automation_runs')
    op.drop_table('automation_linked_accounts')
    op.drop_table('automations')
    op.drop_table('automation_template_apps')
    op.drop_table('automation_templates')
    # ### end Alembic commands ###
