"""Rename file path

Revision ID: 43951112ff89
Revises: a732204a00ab
Create Date: 2025-09-27 14:21:01.911793+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43951112ff89'
down_revision: Union[str, None] = 'a732204a00ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete all existing rows with cascade
    op.execute("DELETE FROM artifacts")
    
    op.add_column('artifacts', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_constraint(op.f('artifacts_filer_path_key'), 'artifacts', type_='unique')
    op.create_unique_constraint('artifacts_file_path_key', 'artifacts', ['file_path'])
    op.drop_column('artifacts', 'filer_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('filer_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('artifacts_file_path_key', 'artifacts', type_='unique')
    op.create_unique_constraint(op.f('artifacts_filer_path_key'), 'artifacts', ['filer_path'], postgresql_nulls_not_distinct=False)
    op.drop_column('artifacts', 'file_path')
    # ### end Alembic commands ###
