"""optimize

Revision ID: 94ec78bdc315
Revises: 921e4f9aad6f
Create Date: 2025-11-20 18:09:25.444732+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94ec78bdc315'
down_revision: Union[str, None] = '921e4f9aad6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_apps_active', 'apps', ['active'], unique=False)
    op.create_index('ix_apps_categories', 'apps', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('ix_automation_runs_automation_started', 'automation_runs', ['automation_id', 'started_at'], unique=False)
    op.create_index('ix_automation_templates_tags', 'automation_templates', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_templates_tags', table_name='automation_templates', postgresql_using='gin')
    op.drop_index('ix_automation_runs_automation_started', table_name='automation_runs')
    op.drop_index('ix_apps_categories', table_name='apps', postgresql_using='gin')
    op.drop_index('ix_apps_active', table_name='apps')
    # ### end Alembic commands ###
