"""add indexing

Revision ID: 921e4f9aad6f
Revises: ac55df85358b
Create Date: 2025-11-15 16:40:00.302394+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921e4f9aad6f'
down_revision: Union[str, None] = 'ac55df85358b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_artifacts_expires_at', 'artifacts', ['expires_at'], unique=False)
    op.create_index('ix_artifacts_run_id', 'artifacts', ['run_id'], unique=False)
    op.create_index('ix_artifacts_user_id', 'artifacts', ['user_id'], unique=False)
    op.create_index('ix_automation_linked_accounts_automation_id', 'automation_linked_accounts', ['automation_id'], unique=False)
    op.create_index('ix_automation_linked_accounts_linked_account_id', 'automation_linked_accounts', ['linked_account_id'], unique=False)
    op.create_index('ix_automation_runs_automation_id', 'automation_runs', ['automation_id'], unique=False)
    op.create_index('ix_automation_runs_automation_status', 'automation_runs', ['automation_id', 'status'], unique=False)
    op.create_index('ix_automation_runs_started_at', 'automation_runs', ['started_at'], unique=False)
    op.create_index('ix_automation_runs_status', 'automation_runs', ['status'], unique=False)
    op.create_index('ix_automations_active', 'automations', ['active'], unique=False)
    op.create_index('ix_automations_created_at', 'automations', ['created_at'], unique=False)
    op.create_index('ix_automations_is_recurring', 'automations', ['is_recurring'], unique=False)
    op.create_index('ix_automations_last_run_status', 'automations', ['last_run_status'], unique=False)
    op.create_index('ix_automations_user_active_recurring', 'automations', ['user_id', 'active', 'is_recurring'], unique=False)
    op.create_index('ix_automations_user_id', 'automations', ['user_id'], unique=False)
    op.create_index('ix_fcm_tokens_token', 'fcm_tokens', ['token'], unique=False)
    op.create_index('ix_fcm_tokens_user_id', 'fcm_tokens', ['user_id'], unique=False)
    op.create_index('ix_functions_active', 'functions', ['active'], unique=False)
    op.create_index('ix_functions_app_id', 'functions', ['app_id'], unique=False)
    op.create_index('ix_functions_app_id_active', 'functions', ['app_id', 'active'], unique=False)
    op.create_index('ix_functions_name', 'functions', ['name'], unique=False)
    op.create_index('ix_linked_accounts_app_id', 'linked_accounts', ['app_id'], unique=False)
    op.create_index('ix_linked_accounts_last_used_at', 'linked_accounts', ['last_used_at'], unique=False)
    op.create_index('ix_linked_accounts_user_id', 'linked_accounts', ['user_id'], unique=False)
    op.create_index('ix_secrets_linked_account_id', 'secrets', ['linked_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secrets_linked_account_id', table_name='secrets')
    op.drop_index('ix_linked_accounts_user_id', table_name='linked_accounts')
    op.drop_index('ix_linked_accounts_last_used_at', table_name='linked_accounts')
    op.drop_index('ix_linked_accounts_app_id', table_name='linked_accounts')
    op.drop_index('ix_functions_name', table_name='functions')
    op.drop_index('ix_functions_app_id_active', table_name='functions')
    op.drop_index('ix_functions_app_id', table_name='functions')
    op.drop_index('ix_functions_active', table_name='functions')
    op.drop_index('ix_fcm_tokens_user_id', table_name='fcm_tokens')
    op.drop_index('ix_fcm_tokens_token', table_name='fcm_tokens')
    op.drop_index('ix_automations_user_id', table_name='automations')
    op.drop_index('ix_automations_user_active_recurring', table_name='automations')
    op.drop_index('ix_automations_last_run_status', table_name='automations')
    op.drop_index('ix_automations_is_recurring', table_name='automations')
    op.drop_index('ix_automations_created_at', table_name='automations')
    op.drop_index('ix_automations_active', table_name='automations')
    op.drop_index('ix_automation_runs_status', table_name='automation_runs')
    op.drop_index('ix_automation_runs_started_at', table_name='automation_runs')
    op.drop_index('ix_automation_runs_automation_status', table_name='automation_runs')
    op.drop_index('ix_automation_runs_automation_id', table_name='automation_runs')
    op.drop_index('ix_automation_linked_accounts_linked_account_id', table_name='automation_linked_accounts')
    op.drop_index('ix_automation_linked_accounts_automation_id', table_name='automation_linked_accounts')
    op.drop_index('ix_artifacts_user_id', table_name='artifacts')
    op.drop_index('ix_artifacts_run_id', table_name='artifacts')
    op.drop_index('ix_artifacts_expires_at', table_name='artifacts')
    # ### end Alembic commands ###
