"""Add categories to automations

Revision ID: d7c0721a92cb
Revises: 58c9c40d859f
Create Date: 2025-08-23 14:01:30.143873+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c0721a92cb'
down_revision: Union[str, None] = '58c9c40d859f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'active')
    # ### end Alembic commands ###
