"""add_subscription_info_in_users

Revision ID: 3c1428aed29e
Revises: bb9aeb3a6966
Create Date: 2025-10-25 14:57:07.966735+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c1428aed29e'
down_revision: Union[str, None] = 'bb9aeb3a6966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Define the new ENUM type
    subscription_status_enum = postgresql.ENUM(
        'ACTIVE', 'TRIALING', 'CANCELLED', 'UNPAID', 'EXPIRED', 
        name='subscriptionstatus'
    )
    # 2. Create the type in the database FIRST
    subscription_status_enum.create(op.get_bind())

    # 3. Now, add the columns (autogenerated commands)
    op.add_column('users', sa.Column('subscription_status', subscription_status_enum, nullable=True))
    op.add_column('users', sa.Column('subscription_product_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_trial', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop columns and index FIRST
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_column('users', 'is_trial')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_product_id')
    op.drop_column('users', 'subscription_status') # This drops the column using the type

    # 2. Define the ENUM type again so we can drop it
    subscription_status_enum = postgresql.ENUM(
        'ACTIVE', 'TRIALING', 'CANCELLED', 'UNPAID', 'EXPIRED', 
        name='subscriptionstatus'
    )
    # 3. Drop the type from the database LAST
    subscription_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###