"""add limits

Revision ID: f40a2985dbc9
Revises: 3c1428aed29e
Create Date: 2025-10-26 11:51:38.995470+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f40a2985dbc9'
down_revision: Union[str, None] = '3c1428aed29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('subscription_period_starts_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_period_starts_at')
    # ### end Alembic commands ###
