"""default security creds

Revision ID: 1d1f5deedcb7
Revises: a67e082479de
Create Date: 2025-08-02 18:18:46.713027+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Make sure this import path is correct for your project structure
from aci.common.db.custom_sql_types import EncryptedSecurityCredentials
from aci.common.enums import SecurityScheme

# revision identifiers, used by Alembic.
revision: str = '1d1f5deedcb7'
down_revision: Union[str, None] = 'a67e082479de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_app_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    # CORRECTED: Added create_type=False to prevent "DuplicateObject" error
    sa.Column('security_scheme', sa.Enum(SecurityScheme, name='securityschemecreds', create_type=False), nullable=False),
    # ADDED: The missing 'credentials' column
    sa.Column('credentials', EncryptedSecurityCredentials(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_unique_constraint('uq_app_configurations_app_id', 'app_configurations', ['app_id'])
    op.drop_column('apps', 'default_security_credentials_by_scheme')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column('apps', sa.Column('default_security_credentials_by_scheme', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint('uq_app_configurations_app_id', 'app_configurations', type_='unique')
    op.drop_table('default_app_credentials')
    # ### end Alembic commands ###
