"""add_internal_usage_metrics

Revision ID: 72a1e765aa18
Revises: f5d60dd40b54
Create Date: 2025-09-02 19:36:34.150154+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72a1e765aa18'
down_revision: Union[str, None] = 'f5d60dd40b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('voice_agent_minutes', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('automation_runs_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('successful_automation_runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_automation_runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stt_audio_minutes', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('tts_characters_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_user_year_month')
    )
    op.create_index('ix_user_usage_user_year_month', 'user_usage', ['user_id', 'year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_usage_user_year_month', table_name='user_usage')
    op.drop_table('user_usage')
    # ### end Alembic commands ###
