version: '3.8'

services:
  # Prometheus, Grafana, Node-Exporter services remain the same...
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitor-net
    deploy:
      mode: global

  loki:
    image: grafana/loki:latest
    volumes:
      - loki_data:/loki
    configs:
      - source: loki_config # This part is correct
        target: /etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    configs:
      - source: promtail_config # This part is correct
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net
    deploy:
      mode: global

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  monitor-net:

# --- CORRECTED SECTION ---
# This tells Swarm to use the configs you created with 'docker config create'
configs:
  loki_config:
    external: true
  promtail_config:
    external: true